{% set version = "1.2.2" %}

package:
  name: jake
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jake/jake-{{ version }}.tar.gz
  sha256: 9568f10f36c2f7e66951f0e81a8602f49ddbf854b565d6b641a959da3ab26eb3

build:
  number: 0
  noarch: python
  entry_points:
    - jake = jake.app:main
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry-core >=1.0.0
  run:
    - python >=3.6
    # these get translated from ~^ to concrete values in poetry-generated setup.py
    - click >=8.0.1,<9.0.0
    - cyclonedx-python-lib >=0.12.0,<0.13.0
    - ossindex-lib >=0.2.1,<0.3.0
    - polling2 >=0.5.0,<0.6.0
    - pyfiglet >=0.8.post1,<0.9
    - pyyaml >=5.4.1,<6.0.0
    - requests >=2.26.0,<3.0.0
    - rich >=10.15.2,<11.0.0
    - tinydb >=4.5.1,<5.0.0

test:
  imports:
    - jake
  commands:
    - pip check
    - jake --version
    - jake --help
  requires:
    - pip

about:
  home: https://github.com/sonatype-nexus-community/jake
  summary: An OSS Index integration to check for vulnerabilities in your Conda environments
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
